#!/usr/bin/env python3
"""Split a firtool-generated CoralNPU .sv bundle into its original files.

firtool concatenates every output file into one .sv, separated by
    // ----- 8< ----- FILE "<path>" ----- 8< -----
The first chunk (before any marker) is the Chisel-generated design itself.

Outputs, under OUT_DIR:
  <Top>.sv, *.sv, *.v, *.svh     design files
  verification/...               firtool assert/assume/cover layers (sim only)
  synth.f                        design only, in bundle order (single compilation unit)
  sim.f                          synth.f + verification layers

Usage: split_generated_sv.py BUNDLE.sv OUT_DIR
"""
import re
import sys
from pathlib import Path

MARKER = re.compile(r'^// ----- 8< ----- FILE "(?P<path>[^"]+)" ----- 8< -----$')


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    bundle, out = Path(sys.argv[1]), Path(sys.argv[2])
    top = bundle.stem

    chunks = [(f"{top}.sv", [])]
    for line in bundle.read_text().splitlines(keepends=True):
        m = MARKER.match(line.rstrip("\n"))
        if m:
            chunks.append((m["path"].removeprefix("./"), []))
        else:
            chunks[-1][1].append(line)

    seen = set()
    design, verif = [], []
    for path, lines in chunks:
        if path in seen:
            sys.exit(f"duplicate file in bundle: {path}")
        seen.add(path)
        dst = out / path
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text("".join(lines))
        # Headers stay in the filelist at their bundle position: some sources
        # (fpnew) use macros from registers.svh without `include-ing it, relying
        # on the bundle being a single compilation unit. Include guards make the
        # later `include "rvv_backend*.svh" lines harmless.
        (verif if path.startswith("verification/") else design).append(path)

    # The design chunk instantiates blackboxes (RstSync, RVV, FPU, Sram) that
    # appear later in the bundle; packages must come first for most tools.
    pkgs = [p for p in design if p.endswith("_pkg.sv")]
    rest = [p for p in design if p not in pkgs]
    header = ["// Generated by scripts/split_generated_sv.py -- do not edit.",
              f"// Source bundle: {bundle.name}", "+incdir+${CORALNPU_RTL}"]
    rel = lambda ps: [f"${{CORALNPU_RTL}}/{p}" for p in ps]
    (out / "synth.f").write_text("\n".join(header + rel(pkgs + rest)) + "\n")
    (out / "sim.f").write_text("\n".join(header + rel(pkgs + rest + verif)) + "\n")

    nhdr = sum(p.endswith(".svh") for p in design)
    print(f"{len(chunks)} files: {len(design) - nhdr} design + {nhdr} headers, "
          f"{len(verif)} verification -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
